# This is a basic workflow to help you get started with Actions

name: Doxygen Action

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]


  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2


    - name: Install Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: doxygen-latex poppler-utils
        version: 1.1


        
    - name: Doxygen Action
      uses: mattnotmitt/doxygen-action@v1.1.0
      with:
        # Path to Doxyfile
        doxyfile-path: "./Doxyfile" # default is ./Doxyfile
        # Working directory
        working-directory: "." # default is .


    - name: Generate Reference Manual
      run: sudo make --directory=documentation/latex

    
    - name: Copy file
      uses: canastro/copy-action@0.0.2
      with:
        source: "documentation/latex/refman.pdf"
        target: "documentation/html/refman.pdf"

    - name: Copy log
      uses: canastro/copy-action@0.0.2
      with:
        source: "documentation/latex/refman.log"
        target: "documentation/html/refman.log"


    - name: Get Notebook Link 
      shell: bash
      run: |
        echo "NOTEBOOK_URL=$(curl -s https://docs.google.com/document/d/1Qi4-ZraS1KN8aG-58iJjD0aQQz0nNSEPkc6Hfz7vbTE/export\?format\=pdf |grep HREF |sed -E "s|.*HREF=\"([^\"]*).*|\1|g")" >> "$GITHUB_ENV"  

    - name: Download Notebook
      uses: wei/curl@master
      with: 
        args: ${{ env.NOTEBOOK_URL }} --output documentation/html/notebook_top.pdf



    - name: Concatenate Manual and Notebook
      run: sudo pdfunite documentation/html/notebook_top.pdf documentation/html/refman.pdf documentation/html/notebook.pdf

    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        # Default Doxyfile build documentation to html directory. 
        # Change the directory if changes in Doxyfile
        publish_dir: ./documentation/html
